deploy:
  stage: deploy
  resource_group: "deploy"
  needs:
    - job: test-frontend
    - job: test-backend
    - job: build-frontend
    - job: build-backend
  before_script:
    - apk add rsync --update
    - eval $(ssh-agent -s)
    # SSH_PRIVATE_KEY must be base64 encoded before added to gitlab variable as 'mask variable': "cat privatekey | base64 -w0" (on mac "cat privatekey | base64 -b0")
    - echo -e "$SSH_PRIVATE_KEY" | base64 -d | ssh-add - > /dev/null
    - mkdir -p ~/.ssh && chmod 700 ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\tUserKnownHostsFile /dev/null" >> ~/.ssh/config
  image:
    name: composer:latest
  cache: [ ]
  variables:
    GIT_STRATEGY: none
  retry:
    max: 2
  script:
    - | 
      if [ -z "$DEPLOYER_SELECTOR" ]; then curl -s https://raw.githubusercontent.com/sourcebrokergit/deployer-typo3-ci/0.0.13/ci/provider/gitlab/scripts/deployer_selector.sh -o deployer_selector_${CI_JOB_ID}.sh && source deployer_selector_${CI_JOB_ID}.sh; rm deployer_selector_${CI_JOB_ID}.sh; fi
      cd ${CI_BUILDS_DIR} && mkdir -p deployer && cd deployer && composer require ${DEPLOYER_INSTALL:-deployer/deployer:^7.5} --verbose --prefer-dist --no-progress --no-interaction --optimize-autoloader
      cd ${CI_PROJECT_DIR} && ${CI_BUILDS_DIR}/deployer/vendor/bin/dep deploy-ci ${DEPLOYER_BT} ${DEPLOYER_OPTIONS} ${DEPLOYER_SELECTOR} -vv
  rules:
    - if: $CI_COMMIT_BRANCH && $CI_COMMIT_BRANCH =~ $DEPLOY_TRIGGER_BY_CI_COMMIT_BRANCH
    - if: $CI_COMMIT_TAG && $CI_COMMIT_TAG =~ $DEPLOY_TRIGGER_BY_CI_COMMIT_TAG
